const USER_ACTIONS_TYPES = {
  POST_USER_LOGIN: "POST_USER_LOGIN",
  POST_USER_LOGIN_SUCCESS: "POST_USER_LOGIN_SUCCESS",
  POST_USER_LOGIN_FAIL: "POST_USER_LOGIN_FAIL",
  // =====================================
  POST_USER_SIGNUP: "POST_USER_SIGNUP",
  POST_USER_SIGNUP_SUCCESS: "POST_USER_SIGNUP_SUCCESS",
  POST_USER_SIGNUP_FAIL: "POST_USER_SIGNUP_FAIL",
  // =====================================
  POST_USER_LOGOUT: "POST_USER_LOGOUT",
  POST_USER_LOGOUT_SUCCESS: "POST_USER_LOGOUT_SUCCESS",
  POST_USER_LOGOUT_FAIL: "POST_USER_LOGOUT_FAIL",
  // =====================================
  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",
};
const CHEMICAL_ACTIONS_TYPES = {
  POST_CHEMICAL: "POST_CHEMICAL",
  POST_CHEMICAL_SUCCESS: "POST_CHEMICAL_SUCCESS",
  POST_CHEMICAL_FAIL: "POST_CHEMICAL_FAIL",
  // =====================================
  GET_CHEMICAL: "GET_CHEMICAL",
  GET_CHEMICAL_SUCCESS: "GET_CHEMICAL_SUCCESS",
  GET_CHEMICAL_FAIL: "GET_CHEMICAL_FAIL",
  // =====================================
  PUT_CHEMICAL: "PUT_CHEMICAL",
  PUT_CHEMICAL_SUCCESS: "PUT_CHEMICAL_SUCCESS",
  PUT_CHEMICAL_FAIL: "PUT_CHEMICAL_FAIL",
  // =====================================
  DELETE_CHEMICAL: "DELETE_CHEMICAL",
  DELETE_CHEMICAL_SUCCESS: "DELETE_CHEMICAL_SUCCESS",
  DELETE_CHEMICAL_FAIL: "DELETE_CHEMICAL_FAIL",
  // =====================================
};
const CHEMICALS_ACTIONS_TYPES = {
  GET_CHEMICALS: "GET_CHEMICALS",
  GET_CHEMICALS_SUCCESS: "GET_CHEMICALS_SUCCESS",
  GET_CHEMICALS_FAIL: "GET_CHEMICALS_FAIL",
};

const TOOLS_ACTIONS_TYPES = {
  GET_TOOLS: "GET_TOOLS",
  GET_TOOLS_SUCCESS: "GET_TOOLS_SUCCESS",
  GET_TOOLS_FAIL: "GET_TOOLS_FAIL",
};
const TOOL_ACTIONS_TYPES = {
  POST_TOOL: "POST_TOOL",
  POST_TOOL_SUCCESS: "POST_TOOL_SUCCESS",
  POST_TOOL_FAIL: "POST_TOOL_FAIL",
  // =====================================
  GET_TOOL: "GET_TOOL",
  GET_TOOL_SUCCESS: "GET_TOOL_SUCCESS",
  GET_TOOL_FAIL: "GET_TOOL_FAIL",
  // =====================================
  PUT_TOOL: "PUT_TOOL",
  PUT_TOOL_SUCCESS: "PUT_TOOL_SUCCESS",
  PUT_TOOL_FAIL: "PUT_TOOL_FAIL",
  // =====================================
  DELETE_TOOL: "DELETE_TOOL",
  DELETE_TOOL_SUCCESS: "DELETE_TOOL_SUCCESS",
  DELETE_TOOL_FAIL: "DELETE_TOOL_FAIL",
  // =====================================
};
export {
  USER_ACTIONS_TYPES,
  CHEMICAL_ACTIONS_TYPES,
  CHEMICALS_ACTIONS_TYPES,
  TOOLS_ACTIONS_TYPES,
  TOOL_ACTIONS_TYPES,
};
