const USER_ACTIONS_TYPES = {
  POST_USER_LOGIN: "POST_USER_LOGIN",
  POST_USER_LOGIN_SUCCESS: "POST_USER_LOGIN_SUCCESS",
  POST_USER_LOGIN_FAIL: "POST_USER_LOGIN_FAIL",
  // =====================================
  POST_USER_SIGNUP: "POST_USER_SIGNUP",
  POST_USER_SIGNUP_SUCCESS: "POST_USER_SIGNUP_SUCCESS",
  POST_USER_SIGNUP_FAIL: "POST_USER_SIGNUP_FAIL",
  // =====================================
  POST_USER_LOGOUT: "POST_USER_LOGOUT",
  POST_USER_LOGOUT_SUCCESS: "POST_USER_LOGOUT_SUCCESS",
  POST_USER_LOGOUT_FAIL: "POST_USER_LOGOUT_FAIL",
};

export { USER_ACTIONS_TYPES };
